[package]
name = "colink-sdk"
version = "0.1.12"
edition = "2021"

[dependencies]
async-trait = "0.1"
base64 = "0.13.0"
chrono = "0.4"
ctrlc = { version = "3.2", features = ["termination"] }
futures-lite = "1.12"
lapin = "2.1"
openssl = "0.10"
prost = "0.10"
rand = { version = "0.8.4", features = ["std_rng"] }
secp256k1 = { version = "0.21.2", features = ["rand-std"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
structopt = "0.3"
tokio = { version = "1.18", features = ["macros", "rt-multi-thread", "rt", "fs"] }
tonic = { version = "0.7", features = ["tls", "tls-roots"] }
tracing = "0.1"
tracing-subscriber = "0.2"

[build-dependencies]
prost-build = "0.10"
tonic-build = "0.7"

[features]
default = ["extensions"]
extensions = ["read_or_wait", "get_participant_id", "lock", "variable_transfer", "registry"]
read_or_wait = []
get_participant_id = []
lock = []
remote_storage = ["read_or_wait"]
variable_transfer = ["read_or_wait", "remote_storage"]
registry = []
