on:
  release:
    types: [released]

name: Publish to crates

jobs:
  check:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
          ssh-key: ${{ secrets.SSH_KEY }}
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Install protobuf
        if: ${{ startsWith(matrix.ci_image, 'ubuntu') }}
        run: sudo apt update && sudo apt install protobuf-compiler -y
      - name: Install protobuf(macos)
        if: ${{ startsWith(matrix.ci_image, 'macos') }}
        run: brew install protobuf
      - name: Publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: cargo publish
